export interface Country {
    code: string;
    label: string;
}

export const COUNTRIES: Country[] = [
    { code: "ALL", label: "All regions" },
    { code: "AR", label: "Argentina" },
    { code: "AU", label: "Australia" },
    { code: "AT", label: "Austria" },
    { code: "BE", label: "Belgium" },
    { code: "BR", label: "Brazil" },
    { code: "CA", label: "Canada" },
    { code: "CL", label: "Chile" },
    { code: "CN", label: "China" },
    { code: "DK", label: "Denmark" },
    { code: "FI", label: "Finland" },
    { code: "FR", label: "France" },
    { code: "DE", label: "Germany" },
    { code: "GR", label: "Greece" },
    { code: "HK", label: "Hong Kong" },
    { code: "IN", label: "India" },
    { code: "ID", label: "Indonesia" },
    { code: "IT", label: "Italy" },
    { code: "JP", label: "Japan" },
    { code: "KR", label: "Korea" },
    { code: "MY", label: "Malaysia" },
    { code: "MX", label: "Mexico" },
    { code: "NL", label: "Netherlands" },
    { code: "NZ", label: "New Zealand" },
    { code: "NO", label: "Norway" },
    { code: "PH", label: "Philippines" },
    { code: "PL", label: "Poland" },
    { code: "PT", label: "Portugal" },
    { code: "RU", label: "Russia" },
    { code: "SA", label: "Saudi Arabia" },
    { code: "ZA", label: "South Africa" },
    { code: "ES", label: "Spain" },
    { code: "SE", label: "Sweden" },
    { code: "CH", label: "Switzerland" },
    { code: "TW", label: "Taiwan" },
    { code: "TR", label: "Turkey" },
    { code: "GB", label: "United Kingdom" },
    { code: "US", label: "United States" },
];
